### ISSUE TITLE
Question: DELETE - NOT CONFIRMED

### ISSUE THREAD

**Issue by membra** [servian/aws-auto-cleanup#104] opened 2022-01-20 03:10 UTC
I have a question about this status -
what exactly does it mean? 

I ran in destroy mode and the resource that was marked like that - was not deleted.

What defines that?

**Comment by mlevit** [comment] 2022-01-24 20:43
`DELETE - NOT CONFIRMED` is the status assigned to CloudFormation Stacks that have been "deleted".

CloudFormation Stacks are deleted asynchronously due to how long they can potentially take to delete. Since AWS Auto Cleanup is run within a Lambda Function, we cannot wait for all Stacks to delete as the Function may hit the 15-minute timeout limit. Hence Stacks are "deleted" and then AWS Auto Cleanup moves on without being able to confirm if the Stacks were actually deleted or not.

**Closed** 2022-02-02 02:36 UTC
Labels: question
